### ISSUE TITLE
Chatbar.tsx:153 Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.

### ISSUE THREAD

**Issue by iischajn** [ivanfioravanti/chatbot-ollama#49]
Chatbar.tsx:153 Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
    at Chatbar (webpack-internal:///./components/Chatbar/Chatbar.tsx:44:79)
    at div
    at main
    at Home (webpack-internal:///./pages/api/home/home.tsx:54:11)
    at QueryClientProvider (webpack-internal:///./node_modules/react-query/es/react/QueryClientProvider.js:39:21)
    at div
    at App (webpack-internal:///./pages/_app.tsx:18:11)
    at I18nextProvider (webpack-internal:///./node_modules/react-i18next/dist/es/I18nextProvider.js:10:19)
    at AppWithTranslation (webpack-internal:///./node_modules/next-i18next/dist/esm/appWithTranslation.js:34:22)
    at PathnameContextProviderAdapter (webpack-internal:///./node_modules/next/dist/shared/lib/router/adapters.js:80:11)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:26:6864)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:26:9247)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:80:1)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:213:11)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:437:11)

**Comment by ivanfioravanti** [comment]
Can you share more details on this one? Was chat very long?

**Comment by AdvaithAtluri** [comment]
yes was it
